# Sets version number from VERSION.txt into a variable. As well as the git commit hash.

steps:
- task: CmdLine@2
  displayName: 'Set Version Number variables for  Windows'
  inputs:
    script: |
        SETLOCAL EnableDelayedExpansion
        set /p _OnnxRuntimeVersion=<$(Build.SourcesDirectory)\VERSION_NUMBER 
        @echo ##vso[task.setvariable variable=OnnxRuntimeVersion;]%_OnnxRuntimeVersion%
        
        FOR /F "tokens=* USEBACKQ" %%F IN (`git rev-parse HEAD`) DO (
            @echo ##vso[task.setvariable variable=OnnxRuntimeGitCommitHash;]%%F
        )
        
    workingDirectory: '$(Build.SourcesDirectory)'
  condition: eq(variables['Agent.OS'], 'Windows_NT') 

- task: CmdLine@2
  displayName: 'Set version number variables for Unix'
  inputs:
    script: |
        _OnnxRuntimeVersion=$(head -1 $(Build.SourcesDirectory)/VERSION_NUMBER) 
        echo "##vso[task.setvariable variable=OnnxRuntimeVersion;]$_OnnxRuntimeVersion"
        
        _OnnxRuntimeGitCommitHash=$(git rev-parse HEAD)
        echo "##vso[task.setvariable variable=OnnxRuntimeGitCommitHash;]$_OnnxRuntimeGitCommitHash"

    workingDirectory: '$(Build.SourcesDirectory)'
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))