# sets variables $(TestDataUrl) and $(TestDataChecksum)

parameters:
  TestDataUrl: https://onnxruntimetestdata.blob.core.windows.net/models/20190327.zip
  TestDataChecksum: 45166d81c021c8aae212b53c92101792

steps:
- task: CmdLine@1
  displayName: 'Set TestDataUrl variable'
  inputs:
    filename: echo
    arguments: '##vso[task.setvariable variable=TestDataUrl;]${{parameters.TestDataUrl}}'

- task: CmdLine@1
  displayName: 'Set TestDataChecksum variable'
  inputs:
    filename: echo
    arguments: '##vso[task.setvariable variable=TestDataChecksum;]${{parameters.TestDataChecksum}}'
